output "resource_group_name" {
  value       = azurerm_resource_group.main.name
  description = "Name of the resource group that hosts the solution."
}

output "backend_container_app_fqdn" {
  value       = module.application.backend_container_app_fqdn
  description = "Internal FQDN of the backend container app."
}

output "frontend_container_app_fqdn" {
  value       = module.application.frontend_container_app_fqdn
  description = "Internal FQDN of the frontend container app."
}

output "mcp_container_app_fqdn" {
  value       = module.application.mcp_container_app_fqdn
  description = "Internal FQDN of the MCP server container app."
}

output "cognitive_account_endpoint" {
  value       = module.foundry.cognitive_account_endpoint
  description = "Azure AI Foundry account endpoint URI."
}

output "embeddings_endpoint" {
  value       = module.foundry.embeddings_endpoint
  description = "Embeddings model endpoint URI (for Azure OpenAI SDK)."
}

output "ssh_tunnel_example" {
  value       = module.jump.tunnel_command_example
  description = "Example command to create SSH tunnel via Azure Bastion for port forwarding."
}


output "generated_config_files" {
  value       = module.config_files.generated_files
  description = "List of configuration files generated by Terraform."
}
