output "generated_files" {
  description = "List of configuration files generated by this module."
  value = [
    local_file.deploy_env.filename,
    local_file.mcp_env.filename,
    local_file.facilitator_env.filename,
    local_file.product_finder_env.filename,
    local_file.bastion_tunnel_script.filename,
  ]
}

output "deploy_env_path" {
  description = "Path to the deploy/.env file for build operations."
  value       = local_file.deploy_env.filename
}

output "mcp_env_path" {
  description = "Path to the MCP server .env file."
  value       = local_file.mcp_env.filename
}
